name: CI para angular
on: push
jobs:
  unit-tests:
   runs-on: ubuntu-latest
   steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Node setup
      uses: actions/setup-node@v2
      with:
       node-version: '16.x'
    - name: install yarn
      run: npm install -g yarn
    - name: Install dependencies yarn
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Run tests
      run: ng test --watch=false --browsers=ChromeHeadlessCI --code-coverage
